Materi 17: Resampling pada data deret waktu (time series data)

Import Modules

In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [4]:
n_rows = 365 * 24 
n_cols = 2         
cols = ['col1', 'col2'] 
df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)
df.index = pd.date_range(start='2023-01-01', periods=n_rows, freq='h')

df.head()

                     col1  col2
2023-01-01 00:00:00     9    16
2023-01-01 01:00:00    16    12
2023-01-01 02:00:00    15     4
2023-01-01 03:00:00     4    15
2023-01-01 04:00:00    11    18

Resampling data dengan interval monthly

In [3]:
df.resample('M')['col1'].sum().to_frame()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24276\985753190.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M')['col1'].sum().to_frame()

            col1
2023-01-31  7653
2023-02-28  6623
2023-03-31  7392
2023-04-30  7068
2023-05-31  7498
2023-06-30  7035
2023-07-31  7480
2023-08-31  7338
2023-09-30  7464
2023-10-31  7562
2023-11-30  7178
2023-12-31  7501

Resampling data dengan interval daily

In [4]:
df.resample('D')['col1'].sum().to_frame()

            col1
2023-01-01   212
2023-01-02   250
2023-01-03   235
2023-01-04   281
2023-01-05   259
...          ...
2023-12-27   232
2023-12-28   274
2023-12-29   235
2023-12-30   272
2023-12-31   231

[365 rows x 1 columns]

Materi 18: Membentuk Dummy Data Frame

Import Modules

In [5]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Membentuk Data Frame dari Dictionary

In [6]:
pd.DataFrame({'col1':[1, 2, 3, 4], 
              'col2':[5, 6, 7, 8]})

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

Membentuk Data Frame dari Numpy Array

In [7]:
n_rows = 5
n_cols = 3
arr = np.random.randint(1, 20, size=(n_rows, n_cols))
arr

array([[ 3, 14,  8],
       [11,  3, 12],
       [10, 18, 17],
       [13, 10,  7],
       [ 1,  4,  7]], dtype=int32)

In [8]:
pd.DataFrame(arr, columns=tuple('ABC'))

    A   B   C
0   3  14   8
1  11   3  12
2  10  18  17
3  13  10   7
4   1   4   7

Membentuk Data Frame dengan memanfaatkan pandas.util.testing

In [9]:
n_rows = 30 
n_cols = 4 
columns = list('ABCD')
data = np.random.randn(n_rows, n_cols)
df = pd.DataFrame(data, columns=columns)

print(df.head())

          A         B         C         D
0 -0.145309  0.257290 -0.924549  0.571541
1  2.570151 -0.935841  1.710293  0.739475
2 -0.567231 -0.879319 -0.604808  0.716391
3 -0.912835 -1.187191  1.228477 -0.389778
4  0.038466  0.723933 -0.688693 -0.200598

In [10]:
n_rows = 5 
data = {
    'A': np.random.randn(n_rows),                 
    'B': np.arange(1, n_rows + 1),                
    'C': pd.date_range('2024-01-01', periods=n_rows), 
    'D': ['foo', 'bar', 'baz', 'qux', 'quux']    
}
df = pd.DataFrame(data)

print(df.head())

          A  B          C     D
0 -0.061310  1 2024-01-01   foo
1 -0.268165  2 2024-01-02   bar
2 -0.375766  3 2024-01-03   baz
3 -0.012721  4 2024-01-04   qux
4 -0.598206  5 2024-01-05  quux

In [11]:
n_rows = 30  
n_cols = 4   
columns = list('ABCD')  
time_index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')  
df = pd.DataFrame(np.random.randn(n_rows, n_cols), index=time_index, columns=columns)

print(df.head())

                   A         B         C         D
2024-01-01  0.364110 -1.114051  0.136724  0.363868
2024-01-02  0.187085 -0.156183 -1.824771  0.574119
2024-01-03 -0.632304 -0.585580  0.449410 -1.384202
2024-01-04  0.901797  0.436681  0.134073 -1.442151
2024-01-05  0.020214 -0.166318 -1.597884 -0.865973

In [12]:
n_rows = 5
n_cols = 4
data = np.random.randn(n_rows, n_cols)
df = pd.DataFrame(data, columns=list('ABCD'))
df.iloc[0, 1] = np.nan
df.iloc[2, 3] = np.nan
df.iloc[4, 0] = np.nan

print(df.head())

          A         B         C         D
0 -0.177406       NaN -0.165461  1.197677
1  0.580617 -1.106436 -0.395955  1.399228
2  0.489834  2.057197  0.187167       NaN
3 -0.802758 -0.929536  0.800753  0.281996
4       NaN -1.263727  0.422914  0.249558

Materi 19: Formatting Tampilan Data Frame

Import Modules

In [9]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [4]:
n_rows = 5
n_cols = 2
cols = ['omset', 'operasional']
df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

   omset  operasional
0      9           15
1      6           11
2     18           12
3     15            4
4      5            5

In [11]:
df['omset'] = df['omset'] * 100_000
df['operasional'] = df['operasional'] * 10_000
df

     omset  operasional
0  1200000       160000
1  1600000        80000
2   700000       190000
3  1700000       100000
4  1100000        80000

In [12]:
n_rows = 365  
df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, 2)), columns=['col1', 'col2'])
df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')
df = df.reset_index().rename(columns={'index': 'tanggal'})

print(df)

       tanggal  col1  col2
0   2024-01-01     3    18
1   2024-01-02    13     2
2   2024-01-03    19    12
3   2024-01-04     5    12
4   2024-01-05     5     2
..         ...   ...   ...
360 2024-12-26     7     9
361 2024-12-27     1    18
362 2024-12-28     3    18
363 2024-12-29    17     4
364 2024-12-30     8    13

[365 rows x 3 columns]

Melakukan Formatting Tampilan Data Frame

In [5]:
formatku = {'tanggal':'{:%d/%m/%y}', 
            'operasional':'Rp {:.2f}',
            'omset':'Rp {:.2f}'}

laporan = df.style.format(formatku)
laporan

In [6]:
type(laporan)

pandas.io.formats.style.Styler

In [7]:
laporan.set_caption('Data Omset dan Operasional')

Materi 20: Menggabungkan (merge) dua Data Frame secara berdampingan

In [8]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [9]:
d1 = {'col1':[1, 2, 3], 
      'col2':[10, 20, 30]}
df1 = pd.DataFrame(d1)
df1

   col1  col2
0     1    10
1     2    20
2     3    30

In [10]:
d2 = {'col3':[4, 5, 6], 
      'col4':[40, 50, 60]}
df2 = pd.DataFrame(d2)
df2

   col3  col4
0     4    40
1     5    50
2     6    60

Menggabungkan (merge) dua Data Frame secara berdampingan

In [11]:
df = pd.merge(df1, df2, left_index=True, right_index=True)
df

   col1  col2  col3  col4
0     1    10     4    40
1     2    20     5    50
2     3    30     6    60